### PR TITLE
feat: added prismjs line numbers

### LINKED ISSUE #22: code block line numbers

### PR DESCRIPTION
**Pull request by anuraghazra**
Hi @bradgarropy, i have added prismjs line-numbers to the site.

closes #22 

Here's how it looks:
bradsite_code

### CODE REVIEW

**Comment by bradgarropy** [comment]
Deploy preview for *bradgarropy* processing.

Building with commit 223c611c7c642f7303c6f273c7cd1fff374ec2a9

https://app.netlify.com/sites/bradgarropy/deploys/5e1eff9a359fdc00086fbfe9

**Comment by bradgarropy** [comment]
Thanks so much for opening this PR! I struggled to implement this correctly in the past.

Looks like your implementation might be suffering from the same issues I saw. If you check out [this post](https://deploy-preview-104--bradgarropy.netlify.com/blog/contentful-preview-api-with-gatsby-netlify#gatsby--contentful-configuration), you'll see that the line numbers drift out of line with the code.

If there's any way you can fix that, I'd be happy to accept the PR!

**Comment by anuraghazra** [comment]
Ohhh i see. Yeah maybe some font-size or line-height issues happening because of unscoped styles?? 🤔 

No problem, I will look into the issue today.

**Comment by anuraghazra** [comment]
Well, I don't know if you noticed but compare the screenshot that I attached to the PR with the deploy preview... Only the deploy preview is shifted, screenshot is fine (which was running in dev mode)

**Comment by bradgarropy** [comment]
Yea, I noticed that. Gotta love those deploy previews!

**Comment by bradgarropy** [comment]
Yea, I noticed that. Gotta love those deploy previews!

**Comment by anuraghazra** [comment]
Hi @bradgarropy, 
i guess i figured it out. for some reason the computed font-size of `code[class*="language-"], pre[class*="language-"]` ended up 14.4px instead of 14px which was causing the line-numbers to shift.

**Comment by bradgarropy** [comment]
I actually enjoy the larger font size! I was considering increasing the size to `15px` or `16px`.

**Comment by bradgarropy** [comment]
Tonight I gave the site a bit of a face lift with a new syntax highlighting theme, selection color, and primary color. I really appreciate your work @anuraghazra, but I like this new theme better without line numbering. I apologize, but I don't think I'll need this PR.

Thank you for your work, you taught me something!

**Comment by anuraghazra** [comment]
Okay no problem :+1: , welcome.

**Pull request closed without merging**
